cars/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("show-person-cars/<str:NID>/", views.showPersonCars, name="show person cars"),
    path("find-person-cars/", views.findPersonCars, name="find person cars"),
    path("debtor-list-dec/", views.debtorCars, name="debtor cars list dec"),
]

dbback/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include, include
from users import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path("headquarters/", include("headquarters.urls")),


    path("home/", v.home, name="home"),
    path("", include("users.urls")),
    path("cameras/", include("cameras.urls")),
    path("cars/", include("cars.urls")),
    path("violations/", include("violations.urls")),
    path("receipts/", include("receipts.urls")),

]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.register, name="signup"),
    path("citizen-signup/", views.citizen_register, name="citizen-signup"),
    path("login/", views.staff_login, name="login"),
    path("citizen-login/", views.citizen_login, name="citizen-login"),
    path("home/", views.home, name="home"),
    path("staff-dashboard/", views.staff_dashboard, name="staff-dashboard"),
    path("citizen-dashboard/", views.citizen_dashboard, name="citizen-dashboard"),
]

users/models.py
from django.db import models
from headquarters.models import *
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from cars.models import Car
from django.utils.timezone import now
from datetime import date

# karkonan - kode meli
class Staff_NID(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	NID = models.CharField(max_length=10, primary_key=True)
	HeadquartersID = models.ForeignKey(Headquarters, on_delete=models.CASCADE)
	Fathername = models.CharField(default="", blank=True, max_length=100)
	Education = models.CharField(default="", blank=True, max_length=50)
	Soldiership = models.CharField(default="", blank=True, max_length=20)
	BirthDate = models.DateField(default=date.today, editable=True, blank=True)
	JoinDate = models.DateTimeField(default=now, editable=True, blank=True)
	Address = models.TextField(default="", blank=True, max_length=500)
	MaritalStatus = models.CharField(default="", blank=True, max_length=50)

# karkonan - kode shenasayi
class Staff_SID(models.Model):
	SID = models.CharField(max_length=10, primary_key=True)
	NationalID = models.OneToOneField(Staff_NID, on_delete=models.CASCADE)

# telephon karkonan
class Staff_tel(models.Model):
	StaffID =  models.ForeignKey(Staff_SID, on_delete=models.CASCADE)
	Telephone = models.CharField(max_length=11, primary_key=True)

# karkonan technecian
class Technician_staff(models.Model):
	StaffID =  models.OneToOneField(Staff_SID, on_delete=models.CASCADE, primary_key=True)
	Expertise = models.CharField(max_length=50)

# karkonan edari
class Administrative_staff(models.Model):
	StaffID =  models.OneToOneField(Staff_SID, on_delete=models.CASCADE, primary_key=True)
	Room = models.IntegerField()
	Post = models.CharField(max_length=50)

# Create your models here.
class Car_owner(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    NID = models.CharField(max_length=10, primary_key=True)
    Sex = models.CharField(max_length=1)
    BirthDate = models.DateTimeField(default=now, editable=True, null=False, blank=False)
    MobilePhone = models.CharField(max_length=11)
    def __str__(self):
        return 'Car_owner ' + str(self.NID)

class Ownership(models.Model):
    NationalID = models.ForeignKey(Car_owner, on_delete=CASCADE)
    CarID = models.ForeignKey(Car, on_delete=CASCADE)
    def __str__(self):
        return 'Ownership ' + str(self.NationalID)  + ' ' + str(self.CarID)
    class Meta:
        unique_together = ("NationalID", "CarID")

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *
from django.forms import ModelForm

CHOICES = [('M','مرد'),('F','زن')]

class Staff_NIDForm(ModelForm):

	class Meta:
		model = Staff_NID
		fields = ('NID', 'HeadquartersID',)

class Citizen_Form(ModelForm):

	Sex = forms.ChoiceField(label='Sex', widget=forms.Select, choices=CHOICES)

	class Meta:
		model = Car_owner
		fields = ('NID', 'MobilePhone', 'Sex')


class NewUserForm(UserCreationForm):
	first_name = forms.CharField(required=True)
	last_name = forms.CharField(required=True)

	class Meta:
		model = User
		fields = ("first_name", "last_name", "username", "password1", "password2")

	def __init__(self, *args, **kwargs):
		super(NewUserForm, self).__init__(*args, **kwargs)

		for fieldname in ['username', 'password1', 'password2']:
			self.fields[fieldname].help_text = None

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		if commit:
			user.save()
		return user

users/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm

def home(request):
	return render (request=request, template_name="users/base.html", context={})

def staff_dashboard(request):
	return render (request=request, template_name="users/staff-dashboard.html", context={})

def citizen_dashboard(request):
	return render (request=request, template_name="users/citizen-dashboard.html", context={})
	
def register(request):
	if request.method == "POST":
		user_form = NewUserForm(request.POST)
		staff_form = Staff_NIDForm(request.POST)

		if user_form.is_valid() and staff_form.is_valid():
			user = user_form.save()
			staff = staff_form.save(commit=False)
			staff.user = user
			staff.save()
			messages.success(request, "Registration successful." )
			return redirect("users:login")

		messages.error(request, "Unsuccessful registration. Invalid information.")

	else:
		user_form = NewUserForm()
		staff_form = Staff_NIDForm()
		

	return render (request=request, template_name="users/signup.html", context={"user_form":user_form, "staff_form" : staff_form})

def citizen_register(request):
	if request.method == "POST":
		user_form = NewUserForm(request.POST)
		citizen_form = Citizen_Form(request.POST)

		if user_form.is_valid() and citizen_form.is_valid():
			user = user_form.save()
			citizen = citizen_form.save(commit=False)
			citizen.user = user
			citizen.save()
			messages.success(request, "Registration successful." )
			return redirect("users:citizen-login")

		messages.error(request, "Unsuccessful registration. Invalid information.")

	else:
		user_form = NewUserForm()
		citizen_form = Citizen_Form()
		

	return render (request=request, template_name="users/citizen-signup.html", context={"user_form":user_form, "citizen_form" : citizen_form})
	
def staff_login(request):

	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)

		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)

			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("users:staff-dashboard")

			messages.error(request,"Invalid username or password.")

		else:
			messages.error(request,"Invalid username or password.")

	login_form = AuthenticationForm()
	return render(request=request, template_name="users/login.html", context={"login_form":login_form})

def citizen_login(request):

	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)

		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)

			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("users:citizen-dashboard")

			messages.error(request,"Invalid username or password.")

		else:
			messages.error(request,"Invalid username or password.")

	login_form = AuthenticationForm()
	return render(request=request, template_name="users/citizen-login.html", context={"login_form":login_form})

users/templates/users/base.html
<html dir="rtl" lang="fa-IR">
    
<head>
    <meta charset="UTF-8">
    <title>صفحه اصلی</title>

    {% load static %}

    <style>
        * {  
            margin: 0;
            border: 0;
            padding: 0;
            outline: 0;
            text-decoration: none;
            box-sizing: border-box;
        }

        body {
            background-image: url("/static/el.jpg");
            background-size: cover;
        }

        nav {
            display: flex;
            background-color: rgb(46, 46, 46);
            flex-direction: row-reverse;
        }

        @media screen and (max-width: 500px) {
            nav{
                flex-direction: column;
            }
        }

        nav a {
            background-color: rgb(46, 46, 46);
            font-size: 18px;
            color: rgb(226, 226, 226);
            padding: 20px;
        }

        .a2:hover {
            background-color: rgb(0, 0, 0);
            color: rgb(226, 226, 226);
        }

        .a2:active {
            color: rgb(255, 255, 255);
        }

        .a3:hover {
            background-color: rgb(0, 0, 0);
            color: rgb(226, 226, 226);
        }

        .a3:active {
            color: rgb(255, 255, 255);
        }

        .a2 {
            background-color: rgb(52, 163, 74);
        }

        .container {
            background: #21ff3352;
            display: flex;
            top: 0px;
            flex-direction: row;
            justify-content: center;
            position: relative;
            border-style: solid;
            border-width: 5px 0px 5px 0px;
            border-color: rgb(0, 73, 4);
        }

        .h1 {
            justify-content: space-between;
            text-align: center;
            margin-bottom: auto;
            margin-top: auto;
        }

        .tehranlogo {
            height: 120px;
            width: 120px;
            margin: 10px;
            top:0; 
	        right:0; 
        }
    </style>

</head>


<body>

    <div class="uppercontainer">
        <img class="tehranlogo" src={% static "tehranlogo.png" %} alt="tehran logo">
        <h1 class="h1">سامانه هوشمند تخلفات دوربینی شهر تهران</h1>
    </div>

    <nav>
        <a class="a2" href="{% url 'users:home' %}">صفحه اصلی</a>
        <a class="a3" href="{% url 'users:signup' %}">ثبت نام کارمندان</a>
        <a class="a3" href="{% url 'users:citizen-signup' %}">ثبت نام مالکان خودرو</a>
        <a class="a3" href="{% url 'users:login' %}">ورود کارمندان</a>
        <a class="a3" href="{% url 'users:citizen-login' %}">ورود مالکان خودرو</a>
        <a class="a3" href="#">ارتباط با ما</a>
    </nav>
</body>
</html>

users/templates/users/citizen-dashboard.html
<!DOCTYPE html>
<html dir="rtl" lang="fa-IR">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>داشبورد مالک خودرو</title>
    <style>
        * {  
            margin: 0;
            border: 0;
            padding: 0;
            outline: 0;
            text-decoration: none;
            box-sizing: border-box;
        }

        body {
            background-image: url("/static/el.jpg");
            background-size: cover;
        }

        nav {
            display: flex;
            background-color: rgb(46, 46, 46);
            flex-direction: row-reverse;
        }

        @media screen and (max-width: 500px) {
            nav{
                flex-direction: column;
            }
        }

        nav a {
            background-color: rgb(46, 46, 46);
            font-size: 18px;
            color: rgb(226, 226, 226);
            padding: 20px;
        }

        .a2:hover {
            background-color: rgb(0, 0, 0);
            color: rgb(226, 226, 226);
        }

        .a2:active {
            color: rgb(255, 255, 255);
        }

        .a3:hover {
            background-color: rgb(0, 0, 0);
            color: rgb(226, 226, 226);
        }

        .a3:active {
            color: rgb(255, 255, 255);
        }

        .a2 {
            background-color: rgb(52, 163, 74);
        }

        .container {
            background: #21ff3352;
            display: flex;
            top: 50px;
            flex-direction: row;
            justify-content: center;
            position: relative;
            border-style: solid;
            border-width: 5px 0px 5px 0px;
            border-color: rgb(0, 73, 4);
        }

        .subcontainer {
            justify-content: space-between;
            padding: 15px;
            width: 900px;
            height: 570px;
            display: flex;
            flex-direction: column;
            text-align: center;
            justify-content:center;
            background: rgb(255, 255, 255);
        }

        .queryrow {
            background: rgb(255, 255, 255) ;
            margin: 15px;
            height: 150px;
            display: flex;
            flex-direction: row;
            justify-content: space-evenly;
        }

        .option {
            background: rgb(163, 163, 163);
            width: 370px;
            padding: 60px;
            border-radius: 5px;

        }

        .optionlink {
            border-radius: 5px;
            width: 350px;
            padding: 60px;
            height: auto;
            font-size: 24px;
            text-align: center;
            background: rgb(190, 190, 190);
            color: rgb(0, 68, 3);
            font-size: 18px;
        }

        .optionlink:hover {
            background: rgb(202, 255, 195);
            border-style: solid;
            border-width: 1px;
            border-color: black;
            color: black;
        }
    </style>
</head>

<body>
    <nav>
        <a class="a3" href="{% url 'users:home' %}">صفحه اصلی</a>
        <a class="a2" href="{% url 'users:citizen-dashboard' %}">حساب کاربری</a>
        <a class="a3" href="#">ویرایش اطلاعات</a>
        <a class="a3" href="#">ارتباط با ما</a>
    </nav>
    <div class="container">
        <div class="subcontainer">
            <div class="queryrow">

                    <a class="optionlink" href="http://127.0.0.1:8000/violations/list-asc/">لیست تمام تخلفات با توجه به مبلغ آن‌ها (صعودی)</a>

                    <a class="optionlink" href="http://127.0.0.1:8000/violations/list-dec/">لیست تمام تخلفات با توجه به مبلغ آن‌ها (نزولی)</a>

            </div>
            <div class="queryrow">

                    <a class="optionlink" href="http://127.0.0.1:8000/cars/find-person-cars/">یافتن تمام خودروهای فرد</a>

                    <a class="optionlink" href="http://127.0.0.1:8000/receipts/find-receipts">پیدا کردن رسید پرداخت یک جریمه خاص</a>

            </div>
            <div class="queryrow">

                    <a class="optionlink" href="#"></a>


                    <a class="optionlink" href="#">#</a>

            </div>
        </div>
    </div>
</body>
</html>

users/templates/users/citizen-login.html
<html dir="rtl" lang="fa-IR">

<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>ورود مالکان خودرو</title>

    <style>
        * {  
            margin: 0;
            border: 0;
            padding: 0;
            outline: 0;
            text-decoration: none;
            box-sizing: border-box;
        }

        body {
            background-image: url("/static/el.jpg");
            background-size: cover;
        }

        .uppercontainer {
            background: #f7f7f700;
            display: flex;
            top: 5px;
            flex-direction: row;
            justify-content: center;
            position: relative;
            height: 150px;
        }

        nav {
            display: flex;
            background-color: rgb(46, 46, 46);
            flex-direction: row-reverse;
        }

        @media screen and (max-width: 500px) {
            nav{
                flex-direction: column;
            }
        }

        nav a {
            background-color: rgb(46, 46, 46);
            font-size: 18px;
            color: rgb(226, 226, 226);
            padding: 20px;
        }

        .a2:hover {
            background-color: rgb(0, 0, 0);
            color: rgb(226, 226, 226);
        }

        .a2:active {
            color: rgb(255, 255, 255);
        }

        .a3:hover {
            background-color: rgb(0, 0, 0);
            color: rgb(226, 226, 226);
        }

        .a3:active {
            color: rgb(255, 255, 255);
        }

        .a2 {
            background-color: rgb(52, 163, 74);
        }

        .container {
            background: #21ff3352;
            display: flex;
            top: 0px;
            flex-direction: row;
            justify-content: center;
            position: relative;
            border-style: solid;
            border-width: 5px 0px 5px 0px;
            border-color: rgb(0, 73, 4);
        }

        .subcontainer {
            justify-content: space-between;
            padding: 15px;
            width: 900px;
            height: 570px;
            display: flex;
            flex-direction: column;
            text-align: center;
            background: rgb(255, 255, 255);
        }

        .innersubcontainer {
            justify-content: space-between;
            border-radius: 5px;
            width: 870px;
            height: 470px;
            display: flex;
            flex-direction: row;
            text-align: center;
            background: rgb(255, 255, 255);
        }

        .centersubcontainer {
            display: flex;
            flex-direction: row;
            text-align: center;
            justify-content: center;
            padding: 5px;
            width: 430px;
            height: 470px;
            margin-right: auto;
            margin-left: auto;
            border-radius: 5px;
            background: rgb(195, 255, 193);
        }

        .tehranlogo {
            height: 120px;
            width: 120px;
            margin: 10px;
            position:fixed; 
	        top:0; 
	        right:0; 
        }

        .h1 {
            justify-content: space-between;
            text-align: center;
            margin-bottom: auto;
            margin-top: auto;
        }

        /* forms styles */
        .box {
            width: 420px;
            height: auto;
            padding: 20px;
            background-color: rgb(255, 255, 255);
            box-shadow: 0px 0px 25px rgb(130, 129, 129);
            border-radius: 6px;
        }

        input {
            width: 100%;
            border: 1px groove rgb(197, 197, 197);
            padding: 5px;
            border-radius: 5px;
            position: relative;
            left: 50%;
            top: 50%;
            transform: translate(-50%, 30%);
        }

        .button {
            /* font-weight: bold;
            position: relative;
            left: 0%;
            top: 70%;
            transform: translate(-50%, 30%);
            background: rgb(0, 170, 9);
            color: #fff; */
            display: inline-block;
            padding: 10px 24px;
            font-size: 10px;
            font-weight: bold;
            cursor: pointer;
            text-align: center;
            text-decoration: none;
            outline: none;
            color: #fff;
            background-color: #4CAF50;
            border: none;
            border-radius: 8px;
            box-shadow: 0 5px #999;
        }
        .button:hover {background-color: #3e8e41}

        .button:active {
            background-color: #3e8e41;
            box-shadow: 0 5px #666;
            transform: translateY(4px);
        }

        .hrlogin {
            padding: 4px;
            border-radius: 5px;
            background-color: rgb(204, 204, 204);
        }
    </style>
</head>

<body>

    <div class="uppercontainer">
        <img class="tehranlogo" src={% static "tehranlogo.png" %} alt="tehran logo">
        <h1 class="h1">سامانه هوشمند تخلفات دوربینی شهر تهران</h1>
    </div>

    <nav>
        <a class="a3" href="{% url 'users:home' %}">صفحه اصلی</a>
        <a class="a3" href="{% url 'users:signup' %}">ثبت نام کارمندان</a>
        <a class="a3" href="{% url 'users:citizen-signup' %}">ثبت نام مالکان خودرو</a>
        <a class="a3" href="{% url 'users:login' %}">ورود کارمندان</a>
        <a class="a2" href="{% url 'users:citizen-login' %}">ورود مالکان خودرو</a>
        <a class="a3" href="#">ارتباط با ما</a>
    </nav>

    <div class="container">

        <div class="subcontainer">

            <div class="innersubcontainer">

                <div class="centersubcontainer">

                    <div class="box"><br>
                        <h3 class="hrlogin">ورود مالکان خودرو</h3><br><br>

                        <form action="{% url 'users:citizen-login' %}" method="post">
                                {% csrf_token %}
                                    <label>نام کاربری</label>
                                    {{ login_form.username }}<br><br>
                                    <label>رمز عبور</label>
                                    {{ login_form.password }}<br><br><br>
                                    <button type="submit" name="save" class="button">ورود</button>
                        </form>

                    </div>

                </div>

            </div>

        </div>

    </div>
    
</body>
</html>

users/templates/users/citizen-signup.html
<html dir="rtl" lang="fa-IR">

<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>ثبت نام مالکان خودرو</title>

    <style>
        * {  
            margin: 0;
            border: 0;
            padding: 0;
            outline: 0;
            text-decoration: none;
            box-sizing: border-box;
        }

        body {
            background-image: url("/static/el.jpg");
            background-size: cover;
        }

        .uppercontainer {
            background: #f7f7f700;
            display: flex;
            top: 5px;
            flex-direction: row;
            justify-content: center;
            position: relative;
            height: 150px;
        }

        nav {
            display: flex;
            background-color: rgb(46, 46, 46);
            flex-direction: row-reverse;
        }

        @media screen and (max-width: 500px) {
            nav{
                flex-direction: column;
            }
        }

        nav a {
            background-color: rgb(46, 46, 46);
            font-size: 18px;
            color: rgb(226, 226, 226);
            padding: 20px;
        }

        .a2:hover {
            background-color: rgb(0, 0, 0);
            color: rgb(226, 226, 226);
        }

        .a2:active {
            color: rgb(255, 255, 255);
        }

        .a3:hover {
            background-color: rgb(0, 0, 0);
            color: rgb(226, 226, 226);
        }

        .a3:active {
            color: rgb(255, 255, 255);
        }

        .a2 {
            background-color: rgb(52, 163, 74);
        }

        .container {
            background: #21ff3352;
            display: flex;
            top: 0px;
            flex-direction: row;
            justify-content: center;
            position: relative;
            border-style: solid;
            border-width: 5px 0px 5px 0px;
            border-color: rgb(0, 73, 4);
        }

        .subcontainer {
            justify-content: space-between;
            padding: 15px;
            width: 900px;
            height: 570px;
            display: flex;
            flex-direction: column;
            text-align: center;
            background: rgb(255, 255, 255);
        }

        .innersubcontainer {
            justify-content: space-between;
            border-radius: 5px;
            width: 870px;
            height: 470px;
            display: flex;
            flex-direction: row;
            text-align: center;
            background: rgb(255, 255, 255);
        }

        .centersubcontainer {
            display: flex;
            flex-direction: row;
            text-align: center;
            justify-content: center;
            padding: 5px;
            width: 550px;
            height: 470px;
            margin-right: auto;
            margin-left: auto;
            border-radius: 5px;
            background: rgb(195, 255, 193);
        }

        .tehranlogo {
            height: 120px;
            width: 120px;
            margin: 10px;
            position:fixed; 
	        top:0; 
	        right:0; 
        }

        .h1 {
            justify-content: space-between;
            text-align: center;
            margin-bottom: auto;
            margin-top: auto;
        }

        /* forms styles */
        .box {
            width: 550px;
            height: auto;
            padding: 20px;
            background-color: rgb(255, 255, 255);
            box-shadow: 0px 0px 25px rgb(130, 129, 129);
            border-radius: 6px;
        }

        input {
            width: 100%;
            border: 1px groove rgb(197, 197, 197);
            padding: 5px;
            border-radius: 5px;
            position: relative;
            left: 50%;
            top: 50%;
            transform: translate(-50%, 30%);
        }

        .button {
            display: inline-block;
            padding: 10px 24px;
            font-size: 10px;
            font-weight: bold;
            cursor: pointer;
            text-align: center;
            text-decoration: none;
            outline: none;
            color: #fff;
            background-color: #4CAF50;
            border: none;
            border-radius: 8px;
            box-shadow: 0 5px #999;
        }
        .button:hover {background-color: #3e8e41}

        .button:active {
            background-color: #3e8e41;
            box-shadow: 0 5px #666;
            transform: translateY(4px);
        }

        .hregister {
            padding: 4px;
            border-radius: 5px;
            background-color: rgb(204, 204, 204);
        }
    </style>
</head>

<body>

    <div class="uppercontainer">
        <img class="tehranlogo" src={% static "tehranlogo.png" %} alt="tehran logo">
        <h1 class="h1">سامانه هوشمند تخلفات دوربینی شهر تهران</h1>
    </div>

    <nav>
        <a class="a3" href="{% url 'users:home' %}">صفحه اصلی</a>
        <a class="a3" href="{% url 'users:signup' %}">ثبت نام کارمندان</a>
        <a class="a2" href="{% url 'users:citizen-signup' %}">ثبت نام مالکان خودرو</a>
        <a class="a3" href="{% url 'users:login' %}">ورود کارمندان</a>
        <a class="a3" href="{% url 'users:citizen-login' %}">ورود مالکان خودرو</a>
        <a class="a3" href="#">ارتباط با ما</a>
    </nav>

    <div class="container">

        <div class="subcontainer">

            <div class="innersubcontainer">

                <div class="centersubcontainer">

                    <div class="box"><br>
                        <h3 class="hregister">ثبت نام مالکان خودرو</h3><br><br>

                        <form action="{% url 'users:citizen-signup' %}" method="post">
                                {% csrf_token %}

                                    <div class="rightside" style="float:right;">
                                        <label>نام</label>
                                        {{ user_form.first_name }}<br><br>
                                        <label>نام خانوادگی</label>
                                        {{ user_form.last_name }}<br><br>
                                        <label>شماره ملی</label>
                                        {{ citizen_form.NID }}<br><br>
                                        <label>تلفن همراه</label>
                                        {{ citizen_form.MobilePhone }}<br><br>
                                        <label>جنسیت</label>
                                        {{ citizen_form.Sex }}
                                    </div>

                                    <div class="lefttside" style="float:left;">
                                        <label>نام کاربری</label>
                                        {{ user_form.username }}<br><br>
                                        <label>رمز عبور</label>
                                        {{ user_form.password1 }}<br><br>
                                        <label>تکرار رمز عبور</label>
                                        {{ user_form.password2 }}<br><br>

                                    </div>
                                    <button type="submit" name="save" class="button">ثبت نام</button>
                        </form>

                    </div>

                </div>

            </div>

        </div>

    </div>
    
</body>
</html>