cars/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("show-person-cars/<str:NID>/", views.showPersonCars, name="show person cars"),
    path("find-person-cars/", views.findPersonCars, name="find person cars"),
    path("debtor-list-dec/", views.debtorCars, name="debtor cars list dec"),
]

dbback/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include, include
from users import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path("headquarters/", include("headquarters.urls")),


    path("home/", v.home, name="home"),
    path("", include("users.urls")),
    path("cameras/", include("cameras.urls")),
    path("cars/", include("cars.urls")),
    path("violations/", include("violations.urls")),
    path("receipts/", include("receipts.urls")),

]

receipts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("show-receipts/<str:FID>/", views.showReceipts, name="show receipt of a fine"),
    path("find-receipts/", views.findReceipts, name="find receipt of a fine"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.register, name="signup"),
    path("citizen-signup/", views.citizen_register, name="citizen-signup"),
    path("login/", views.staff_login, name="login"),
    path("citizen-login/", views.citizen_login, name="citizen-login"),
    path("home/", views.home, name="home"),
    path("staff-dashboard/", views.staff_dashboard, name="staff-dashboard"),
    path("citizen-dashboard/", views.citizen_dashboard, name="citizen-dashboard"),
]

receipts/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from cameras.models import Camera
from violations.models import Violation
from django.utils.timezone import now
from fines.models import Fine1

# Create your models here.
class Receipt1(models.Model):
    ReceiptID = models.IntegerField(blank=False, null=False, unique=True)
    FineID = models.ForeignKey(Fine1, on_delete=CASCADE, null=False, blank=False)
    CameraID = models.ForeignKey(Camera, on_delete=CASCADE, null=False, blank=False)
    ViolationID = models.ForeignKey(Violation, on_delete=CASCADE, null=False, blank=False)
    def __str__(self):
        return 'Receipt1 ' + str(self.ReceiptID) 
    class Meta:
        unique_together = ("ReceiptID", "FineID", "CameraID", "ViolationID")

class Receipt2(models.Model):
    RID = models.IntegerField(blank=False, null=False, unique=True)
    AccNum = models.CharField(max_length=18, blank=False, null=False)
    PayNum = models.CharField(max_length=18, blank=False, null=False)
    Branch = models.IntegerField(blank=False, null=False)
    PaymentDate = models.DateTimeField(default=now, editable=True, null=False, blank=False)
    def __str__(self):
        return 'Receipt2 ' + str(self.RID) 

receipts/forms.py
from django import forms

class FindReceiptsFrom(forms.Form):
    FID = forms.CharField(label="شماره جریمه")

receipts/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from .models import *
from violations.models import *
from fines.models import *
from receipts.models import *
from .forms import FindReceiptsFrom

def showReceipts(response, FID):
	receiptsList = []
	try:
		receipts1 = Receipt1.objects.filter(FineID=FID)
	except Receipt1.DoesNotExist:
		return render(response, "receipts/receipts-not-exist.html", {"message":"رسید مورد نظر یافت نشد!"})
	for r in receipts1:
		receipts2 = Receipt2.objects.filter(RID=r.ReceiptID)
		receiptsList.append(receipts2.RID)
	return render(response, "receipts/show-receipts.html", {"receiptsList":receiptsList})

def findReceipts(response):
	if response.method == "POST":
		form = FindReceiptsFrom(response.POST)    
		if form.is_valid():
			FID = form.cleaned_data["FID"]
		return HttpResponseRedirect("/receipts/show-receipts/%s/" %FID)

	else:
		form = FindReceiptsFrom()  
		return render(response, "receipts/find-receipts.html", {"form":form})

receipts/templates/receipts/find-receipts.html
<!DOCTYPE html>
<html dir="rtl" lang="fa-IR">
<head>
    <meta charset="UTF-8">
    <title>جست و جوی رسیدهای پرداخت</title>
    <style>
        * {  
    margin: 0;
    border: 0;
    padding: 0;
    outline: 0;
    text-decoration: none;
    box-sizing: border-box;
}

body {
    background-image: url("/static/el.jpg");
    background-size: cover;
}

nav {
    display: flex;
    background-color: rgb(46, 46, 46);
    flex-direction: row-reverse;
}

@media screen and (max-width: 500px) {
    nav{
        flex-direction: column;
    }
}

nav a {
    background-color: rgb(46, 46, 46);
    font-size: 18px;
    color: rgb(226, 226, 226);
    padding: 20px;
}

.a2:hover {
    background-color: rgb(0, 0, 0);
    color: rgb(226, 226, 226);
}

.a2:active {
    color: rgb(255, 255, 255);
}

.a3:hover {
    background-color: rgb(0, 0, 0);
    color: rgb(226, 226, 226);
}

.a3:active {
    color: rgb(255, 255, 255);
}

.a2 {
    background-color: rgb(52, 163, 74);
}

.container {
    background: #21ff3352;
    top: 50px;
    display: flex;
    flex-direction: row;
    text-align: center;
    justify-content: center;
    position: relative;
    border-style: solid;
    border-width: 5px 0px 5px 0px;
    border-color: rgb(0, 73, 4);
}

.subcontainer {
    padding: 15px;
    width: 900px;
    height: auto;
    display: flex;
    flex-direction: column;
    text-align: center;
    justify-content: center;
    background: rgb(177, 177, 177);
}

.item {
    justify-content: space-between;
    display: flex;
    flex-direction: row;
    border-radius: 5px;
    width: 840px;
    padding: 40px;
    height: 100px;
    font-size: 24px;
    text-align: center;
    margin: 15px;
    background: rgb(190, 190, 190);
    color: rgb(0, 68, 3);
    font-size: 20;
}

    </style>
</head>
<body>
    <nav>
        <a class="a3" href="{% url 'users:home' %}">صفحه اصلی</a>
        <a class="a3" href="{% url 'users:citizen-dashboard' %}">حساب کاربری</a>
        <a class="a3" href="#">ویرایش اطلاعات</a>
        <a class="a3" href="#">ارتباط با ما</a>
    </nav>
    <div class="container">
        <div class="subcontainer">
            {% block find-receipts %}
                <form method="post" action="/receipts/find-receipts/">
                    {% csrf_token %}
                    {{form}}
                    <button type="submit", name="save">بگرد</button>
                </form>
            {% endblock %}
        </div>
    </div>
</body>
</html>

receipts/templates/receipts/receipts-not-exist.html
<!DOCTYPE html>
<html dir="rtl" lang="fa-IR">
<head>
    <meta charset="UTF-8">
    <title>پیدا نشد</title>
    <style>
        * {  
    margin: 0;
    border: 0;
    padding: 0;
    outline: 0;
    text-decoration: none;
    box-sizing: border-box;
}

body {
    background-image: url("el.jpg");
    background-size: cover;
}

nav {
    display: flex;
    background-color: rgb(46, 46, 46);
    flex-direction: row-reverse;
}

@media screen and (max-width: 500px) {
    nav{
        flex-direction: column;
    }
}

nav a {
    background-color: rgb(46, 46, 46);
    font-size: 18px;
    color: rgb(226, 226, 226);
    padding: 20px;
}

.a2:hover {
    background-color: rgb(0, 0, 0);
    color: rgb(226, 226, 226);
}

.a2:active {
    color: rgb(255, 255, 255);
}

.a3:hover {
    background-color: rgb(0, 0, 0);
    color: rgb(226, 226, 226);
}

.a3:active {
    color: rgb(255, 255, 255);
}

.a2 {
    background-color: rgb(52, 163, 74);
}

.container {
    background: #21ff3352;
    top: 50px;
    display: flex;
    flex-direction: row;
    text-align: center;
    justify-content: center;
    position: relative;
    border-style: solid;
    border-width: 5px 0px 5px 0px;
    border-color: rgb(0, 73, 4);
}

.subcontainer {
    padding: 15px;
    width: 900px;
    height: auto;
    display: flex;
    flex-direction: column;
    text-align: center;
    justify-content: center;
    background: rgb(177, 177, 177);
}

.item {
    justify-content: space-between;
    display: flex;
    flex-direction: row;
    border-radius: 5px;
    width: 840px;
    padding: 40px;
    height: 100px;
    font-size: 24px;
    text-align: center;
    margin: 15px;
    background: rgb(190, 190, 190);
    color: rgb(0, 68, 3);
    font-size: 20;
}

    </style>
</head>
<body>
    <nav>
        <a class="a3" href="{% url 'users:home' %}">صفحه اصلی</a>
        <a class="a3" href="{% url 'users:citizen-dashboard' %}">حساب کاربری</a>
        <a class="a3" href="#">ویرایش اطلاعات</a>
        <a class="a3" href="#">ارتباط با ما</a>
    </nav>
    <div class="container">
        <div class="subcontainer">
            {% block find-receipts %}
                {{message}}
            {% endblock %}
        </div>
    </div>
</body>
</html>

receipts/templates/receipts/show-receipts.html
<!DOCTYPE html>
<html dir="rtl" lang="fa-IR">
<head>
    <meta charset="UTF-8">
    <title>رسیدهای پرداخت</title>
    <style>
        * {  
    margin: 0;
    border: 0;
    padding: 0;
    outline: 0;
    text-decoration: none;
    box-sizing: border-box;
}

body {
    background-image: url("/static/el.jpg");
    background-size: cover;
}

nav {
    display: flex;
    background-color: rgb(46, 46, 46);
    flex-direction: row-reverse;
}

@media screen and (max-width: 500px) {
    nav{
        flex-direction: column;
    }
}

nav a {
    background-color: rgb(46, 46, 46);
    font-size: 18px;
    color: rgb(226, 226, 226);
    padding: 20px;
}

.a2:hover {
    background-color: rgb(0, 0, 0);
    color: rgb(226, 226, 226);
}

.a2:active {
    color: rgb(255, 255, 255);
}

.a3:hover {
    background-color: rgb(0, 0, 0);
    color: rgb(226, 226, 226);
}

.a3:active {
    color: rgb(255, 255, 255);
}

.a2 {
    background-color: rgb(52, 163, 74);
}

.container {
    background: #21ff3352;
    top: 50px;
    display: flex;
    flex-direction: row;
    text-align: center;
    justify-content: center;
    position: relative;
    border-style: solid;
    border-width: 5px 0px 5px 0px;
    border-color: rgb(0, 73, 4);
}

.subcontainer {
    padding: 15px;
    width: 900px;
    height: auto;
    display: flex;
    flex-direction: column;
    text-align: center;
    justify-content: center;
    background: rgb(255, 255, 255);
}

.item {
    justify-content: space-between;
    display: flex;
    flex-direction: row;
    border-radius: 5px;
    width: 840px;
    padding: 40px;
    height: 100px;
    font-size: 24px;
    text-align: center;
    margin: 15px;
    background: rgb(190, 190, 190);
    color: rgb(0, 68, 3);
    font-size: 20;
}

    </style>
</head>
<body>
    <nav>
        <a class="a3" href="{% url 'users:home' %}">صفحه اصلی</a>
        <a class="a3" href="{% url 'users:citizen-dashboard' %}">حساب کاربری</a>
        <a class="a3" href="#">ویرایش اطلاعات</a>
        <a class="a3" href="#">ارتباط با ما</a>
    </nav>
    <div class="container">
        <div class="subcontainer">
            <div class="item">
                <h6>پذیرنده</h6>
                <h6>پرداخت کننده</h6>
                <h6>کد شعبه</h6>
                <h6>زمان پرداخت</h6>
            </div>
            {% block receiptsList %}
                {% for i in receiptsLists%}
                <div class="item">
                    <h6>{{i.AccNum}}</h6>
                    <h6>{{i.PayNum}}</h6>
                    <h6>{{i.Branch}}</h6>
                    <h6>{{i.PaymentDate}}</h6>
                </div>
                {% endfor %}
            {% endblock %}
        </div>
    </div>
</body>
</html>